### ISSUE TITLE
Question: Can I use different SSH keys for submodules?

### ISSUE THREAD

**Issue by sdaberdaku** [kubernetes/git-sync#924] opened 2024-10-16 16:10 UTC
Hello all, 

In my setup I have a base private repository (let's call it A), and two child repositories (B and C) that are also private. Each of them has a public/private ssh key pair, and I've already configured the public keys in the corresponding repositories. I am trying to clone A with its submodules (`--submodules=recursive`).
 
I tried setting `--ssh-key-file=[/etc/git-secret/A-ssh,/etc/git-secret/B-ssh,/etc/git-secret/C-ssh]`, but only the first repo A is cloned, and the submodules fail to clone. If I change the order of the keys, then cloning A also fails. Is there a way to tell git-sync which key to use for which repo? I tried overriding the `~/.ssh/config` file but it didn't help.

Any help is greatly appreciated!

**Comment by thockin** [comment] 2024-10-17 00:08
Yes!  I even have an e2e test for this.

https://github.com/kubernetes/git-sync/blob/master/test_e2e.sh#L3036-L3044

The docs say this:

```
    --ssh-key-file <string>, $GITSYNC_SSH_KEY_FILE                                                                                                                          
            The SSH key(s) to use when using git over SSH.  This flag may be
            specified more than once and the environment variable will be
            parsed like PATH - using a colon (':') to separate elements.  If
            not specified, this defaults to "/etc/git-secret/ssh".
```

Specifically "This flag may be specified more than once".

I am happy, for once, to already have the feature someone needs :)

**Comment by sdaberdaku** [comment] 2024-10-17 05:53
I am specifying the paths with the env variable separating them with : and only the first SSH key seems to be used. How does git-sync know which key to use for which repo?

**Comment by thockin** [comment] 2024-10-17 16:33
Hmm.  I have an e2e which is SUPPOSED to cover this.

```
$ ./test_e2e.sh submodule_sync_over_ssh_different_keys
making bin/linux_amd64/git-sync
container: e2e/git-sync:_home_thockin_src_git-sync-v4__linux_amd64


test root is /tmp/git-sync-e2e.224902972

testcase submodule_sync_over_ssh_different_keys: PASS
```

The test is:

```
    GIT_SYNC \
        --period=100ms \
        --repo="test@$IP:/git/repo" \
        --root="$ROOT" \
        --link="link" \
        --ssh-key-file="/ssh/secret.1" \
        --ssh-key-file="/ssh/secret.2" \
        --ssh-key-file="/ssh/secret.3" \                                                                                                                                    
        --ssh-known-hosts=false \
```

Removing any one of those keys fails the test.

What's happening internally is that we build up `$GIT_SSH_COMMAND` with a series of `-i` flags for each key.  Can you run this with `-v9` (this will log the GIT_SSH_COMMAND and a lot of other stuff) and post logs?

**Comment by sdaberdaku** [comment] 2024-10-17 19:35
Hello @thockin,

I just tested this with the following command:
```shell
docker run \
    -v $DIR:/tmp/git \
    -u$(id -u):$(id -g) \
    registry.k8s.io/git-sync/git-sync:v4.3.0 \
        --repo=git@github.com:myOrg/repo-A.git \
        --root=/tmp/git/root \
        --period=30s \
        --submodules=recursive \
        --ssh-key-file=/tmp/git/ssh-keys/a-key \
        --ssh-key-file=/tmp/git/ssh-keys/b-key \
        --ssh-key-file=/tmp/git/ssh-keys/c-key \
        --ssh-known-hosts=false \
        --add-user \
        -v9
```
The private key files all have 600 permissions.
Here is the log: 
[git-sync-logs.txt](https://github.com/user-attachments/files/17421539/git-sync-logs.txt)

As I mentioned, repo-A is cloned, but then git-sync fails with the submodules.
Thanks for the support!

**Comment by thockin** [comment] 2024-10-17 20:52
`"setting $GIT_SSH_COMMAND","value":"ssh -i /tmp/git/ssh-keys/a-key -i /tmp/git/ssh-keys/b-key -i /tmp/git/ssh-keys/c-key -o StrictHostKeyChecking=no"`

It looks like the plumbing is good, at least.

Do those files actually EXIST?

You can try something like adding `--env "GIT_SSH_COMMAND=ssh -vvv"` to that docker command, which will add a LOT of debug info to the SSH, and you can look for things like `"Warning: Identity file /tmp/git/ssh-keys/b-key not accessible: No such file or directory."`

**Comment by thockin** [comment] 2024-10-17 21:03
I can add debugging in this path, but until then, you can check by hand :)

**Comment by sdaberdaku** [comment] 2024-10-17 21:33
Here are the verbose logs:
[git-sync-logs-vvv.txt](https://github.com/user-attachments/files/17423164/git-sync-logs-vvv.txt)

**Comment by sdaberdaku** [comment] 2024-10-17 21:36
by the way, all three private ssh key files exist. I repeated this experiment both on kubernetes and locally. (for now on kubernetes I switched to the github app authentication -- I created a github app, associated it with my three repos and added the creds to git-sync, it works like a charm).
I still would like to use ssh keys because I can generate them with terraform without manual intervention.

**Comment by thockin** [comment] 2024-10-17 23:00
That log shows success of the SSH authentication. It looks like a GitHub authorization failure. The keys are valid but not authorized. Are you sending multiple github.com keys? I don't know if git is smart enough to use some keys for some operations and other keys for other operations. It just tries them all.

**Comment by sdaberdaku** [comment] 2024-10-18 07:28
In GitHub you cannot use the same deploy key in more than one repository. So I have created three key pairs, and loaded the public key A to the parent repo, then keys B and C to the submodule repos. The keys all work for the respective repos, I've tried them manually one by one and they work.

When I change the order of the keys, the parent repo fails to clone as well. By looking at the logs, I see `Authenticated to github.com ([140.82.121.4]:22)` but then GitHub is probably using the first key for the authorization step which then fails. 

I would argue at this point that this is not  a git-sync bug, but a GitHub related issue. Unless there is some flag or option that you are aware of that could instruct GH to try authorization with multiple keys.

Anyway, I would like to thank you very much for your patience and support! This has been enlightening!

**Comment by thockin** [comment] 2024-10-18 15:11
I'm glad we figured it out, at least identified the problem. I don't know how to fix it. SSH keys are generally associated with a principal, a human or a bot, rather than a specific repository. I don't know how I would express to get in a way that it could pass down to SSH how to handle multiple keys which all authenticate but have different authorizations.  All SSH knows is that the key was accepted by the server. 

If there is a way to tell git to tell SSH which specific key to use for each operation, I could look at supporting that. But I don't know how to do it right now.

**Comment by thockin** [comment] 2024-10-18 15:14
https://gist.github.com/alejandro-martin/aabe88cf15871121e076f66b65306610

That seems to suggest that it is possible, but needs to be done through the SSH config. I don't know if that's something git sync should try to handle, or if that is something you should craft on your own and mount as a volume. It's a pretty unique situation :)

**Comment by thockin** [comment] 2024-10-18 15:16
I'm going to close this for now. We seem to have identified the root cause and a potential workaround. If you dig into this and think there might be a clean way to get git-sync to support this, I'm open to ideas, but the solution has to be proportional to the problem, and this is not a huge problem for many people, I'm sorry to say :)

**Closed** 2024-10-18 15:16 UTC

**Comment by sdaberdaku** [comment] 2024-10-18 17:27
> gured it out, at least identified the problem. I don't know how to fix it. SSH keys are generally associated with a principal, a human or a bot, rather than a specific repository. I don't know how I would express to get in a way that it could pass down to SSH how to handle multiple keys which all authenticate but have different authorizations. All SSH knows is that the key was accepted by the server.
> 
> If there is a way to tell git to tell SSH which specific key to use for each operation, I could look at supporting that. But I don't know how to do it right now.

I've tried this with the git-sync container and it doesn't work because it requires ssh-agent.

**Comment by thockin** [comment] 2024-10-18 23:47
https://gist.github.com/alejandro-martin/aabe88cf15871121e076f66b65306610 looks like it should work without ssh-agent, but I am not equipped to test it manually right now.

**Comment by FleischerT** [comment] 2024-11-20 15:15
> https://gist.github.com/alejandro-martin/aabe88cf15871121e076f66b65306610 looks like it should work without ssh-agent, but I am not equipped to test it manually right now.

This solution could work, but at the moment, the command will include -i /etc/git-secret/ssh, which likely overrides the settings in the SSH config file. The debug output shows the following:

setting GIT_SSH_COMMAND, value: ssh -v -F /tmp/.ssh/config -i /etc/git-secret/ssh -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/etc/git-secret/known_hosts."

**Comment by thockin** [comment] 2024-11-20 16:00
I guess I do not know how to specify multiple keys for git to use, but different keys for different URLs.  I don't have an easy reproduction for this.

The best thing you, or someone, could do would be to help craft an e2e test that models this situation and fails.
