### ISSUE TITLE
is git-sync copying files as a root user?

### ISSUE THREAD

**Issue by VikramTiwari** [kubernetes/git-sync#43] opened 2017-03-04 07:21 UTC
If this is true then `git-sync` cannot be used for the static-file based server along with nginx.

- git-sync copies files as a root user in a volume
- If I attach that volume to nginx then it gives 403 forbidden error

Could there be any other issue for this behaviour?

**Comment by thockin** [comment] 2017-03-06 04:27
Run git-sync as non-root, or set the gsGID ?

**Comment by VikramTiwari** [comment] 2017-03-06 04:30
@thockin Yes, that is doable. But, shouldn't that be the default? Can't think of a reason why files should be copied as root.

**Comment by thockin** [comment] 2017-03-06 04:34
We don't know what UID to run as unless you tell it...

**Comment by VikramTiwari** [comment] 2017-03-06 04:37
Ah! That makes sense. Will try and confirm if it works.

**Comment by stp-ip** [comment] 2017-03-22 03:50
This is mostly a duplicate of #38.

Documentation for workarounds or a default fix will be added as part f #38.

**Closed by stp-ip** 2017-03-22 03:50 UTC
